// Copyright (c) 2026 Tim Molteno <tim@elec.ac.nz>
// SPDX-License-Identifier: GPL-3.0

//! ACR (Acquisition Correlation Ratio) C/N0 estimation.
//!
//! Implements the method described in:
//!
//!   Ma Y, Li H, Zhou Z, Lu M (2024) "C/N0 estimation based on acquisition
//!   correlation ratio for short GNSS data."  GPS Solutions 28:143.
//!   https://doi.org/10.1007/s10291-024-01666-y
//!
//! The ACR method estimates C/N0 from the ratio of the global correlation
//! peak V^m to the largest off-peak correlation V^s at the same frequency.
//!
//! r_A = (V^m / V^s)² is the squared ratio of correlation magnitudes.
//! V^m is proportional to sqrt(I²+Q²) at the correlation peak.
//! V^s is proportional to sqrt(I²+Q²) at the largest off-peak (>1 chip).
//!
//! The r_A → C/N0 mapping depends on the coherent integration time T_coh
//! (the peak's non-centrality λ0 = 2·Nc·T_coh·C/N0, paper eq. 29) and on
//! the code's autocorrelation sidelobe structure, so a separate lookup
//! table is used per constellation.  The tables live in `acr_tables.rs`
//! and are generated by Monte Carlo simulation of the production
//! acquisition functions (`examples/gen_acr_tables.rs`) at the T_coh each
//! constellation actually uses (two code periods).

#[path = "acr_tables.rs"]
mod acr_tables;

pub use acr_tables::{
    BEIDOU_B1C_ACR_TABLE, GALILEO_E1C_ACR_TABLE, GPS_L1C_ACR_TABLE, GPS_L1_CA_ACR_TABLE,
};

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Estimate C/N0 (dB-Hz) from the acquisition correlation ratio
/// `r_a = (V^m / V^s)²` where V^m is the global correlation peak magnitude
/// and V^s is the largest off-peak (>1 chip away) correlation magnitude
/// at the same frequency.
///
/// `table` must be the lookup table for the constellation's coherent
/// integration time and code family (see `acr_tables`).
///
/// Uses linear interpolation in log(r_A) space.
///
/// Returns `None` if r_a ≤ 1.0 (below theoretical cut-off).
pub fn estimate_cn0(r_a: f64, table: &[(f64, f64)]) -> Option<f64> {
    if r_a <= 1.0 || !r_a.is_finite() {
        return None;
    }

    let first = table.first().unwrap();
    let last = table.last().unwrap();

    if r_a <= first.0 {
        return Some(first.1);
    }
    if r_a >= last.0 {
        return Some(last.1);
    }

    // Binary search for interpolation bracket
    let idx = table.partition_point(|&(r, _)| r < r_a);
    if idx == 0 {
        return Some(first.1);
    }
    if idx >= table.len() {
        return Some(last.1);
    }

    let (r_lo, cn0_lo) = table[idx - 1];
    let (r_hi, cn0_hi) = table[idx];

    // Linear interpolation in log(r_A) space for smoother results
    let log_ra = r_a.ln();
    let log_lo = r_lo.ln();
    let log_hi = r_hi.ln();
    let t = (log_ra - log_lo) / (log_hi - log_lo);
    let cn0 = cn0_lo + t * (cn0_hi - cn0_lo);

    Some(cn0.clamp(20.0, 70.0))
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn all_tables() -> [&'static [(f64, f64)]; 4] {
        [
            GPS_L1_CA_ACR_TABLE,
            GALILEO_E1C_ACR_TABLE,
            BEIDOU_B1C_ACR_TABLE,
            GPS_L1C_ACR_TABLE,
        ]
    }

    #[test]
    fn test_lookup_tables_monotonic() {
        for table in all_tables() {
            assert!(table.len() >= 10, "table too short");
            assert!(table[0].0 > 1.0, "table must start above the r_A=1 cut-off");
            for w in table.windows(2) {
                assert!(w[0].0 < w[1].0, "r_A not monotonic: {} -> {}", w[0].0, w[1].0);
                assert!(w[0].1 < w[1].1, "CN0 not monotonic: {} -> {}", w[0].1, w[1].1);
            }
        }
    }

    #[test]
    fn test_estimate_cn0_below_cutoff() {
        for table in all_tables() {
            assert!(estimate_cn0(0.5, table).is_none());
            assert!(estimate_cn0(1.0, table).is_none());
            assert!(estimate_cn0(f64::NAN, table).is_none());
        }
    }

    #[test]
    fn test_estimate_cn0_returns_table_points() {
        for table in all_tables() {
            // Exact table entries round-trip.
            for &(r, cn0) in table.iter().step_by(7) {
                assert_eq!(estimate_cn0(r, table).unwrap(), cn0);
            }
            // Below the first entry: floor at the first C/N0.
            let (r_first, cn0_first) = table[0];
            let r_mid = 0.5 * (1.0 + r_first);
            assert_eq!(estimate_cn0(r_mid, table).unwrap(), cn0_first);
        }
    }

    #[test]
    fn test_estimate_cn0_saturation() {
        for table in all_tables() {
            let (r_last, cn0_last) = table[table.len() - 1];
            // Above the max table value should clamp to max C/N0.
            assert_eq!(estimate_cn0(r_last * 10.0, table).unwrap(), cn0_last);
        }
    }

    #[test]
    fn test_estimate_cn0_gps_mid_range() {
        // r_A ≈ 4.17 corresponds to 45 dB-Hz in the one-bit 2 ms GPS table.
        let c = estimate_cn0(4.1725, GPS_L1_CA_ACR_TABLE).unwrap();
        assert!((c - 45.0).abs() < 0.3, "CN0 = {c} for r_a=4.1725");
        // r_A ≈ 11.45 corresponds to 50 dB-Hz.
        let c = estimate_cn0(11.4497, GPS_L1_CA_ACR_TABLE).unwrap();
        assert!((c - 50.0).abs() < 0.3, "CN0 = {c} for r_a=11.4497");
    }

    #[test]
    fn test_estimate_cn0_interpolation_monotonic() {
        // Interpolation between adjacent brackets must be monotonic.
        let table = GPS_L1_CA_ACR_TABLE;
        let mut prev = table[0].1;
        let mut r = table[0].0;
        while r < table[table.len() - 1].0 {
            r *= 1.01;
            let c = estimate_cn0(r, table).unwrap();
            assert!(c >= prev - 1e-9, "non-monotonic at r_a={r}: {c} < {prev}");
            prev = c;
        }
    }
}
